version: '3'
services:
  mnist_db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${APP_DB},${TEST_DB}
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
      - ./db/sql:/docker-entrypoint-initdb.d/sql
  mnist_api:
    image: maven:3.6.3-openjdk-8
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ["mvn",
                 "compile",
                 "spring-boot:run",
                 "-Dspring-boot.run.arguments=--POSTGRES_USER=$POSTGRES_USER,--POSTGRES_PASSWORD=$POSTGRES_PASSWORD,--APP_DB=$APP_DB,--TEST_DB=$TEST_DB"]